
<div class="contentwidget">
	<img src="images/topbild.jpg" alt="Super tolles Inhaltsbild mit toll bedeutungsschwangerem Alternativtext" class="lb1 flexible">
	<img src="images/grosses-contentbild.jpg" alt="Super tolles Inhaltsbild mit toll bedeutungsschwangerem Alternativtext" style="display:none" class="lb1">
	<img src="images/fackelmann.jpg" alt="Super tolles Inhaltsbild mit toll bedeutungsschwangerem Alternativtext" style="display:none" class="lb1">
	<img src="images/team-beispielbild.jpg" alt="Super tolles Inhaltsbild mit toll bedeutungsschwangerem Alternativtext" style="display:none" class="lb1">
		<header>
	    <small>Der Erlös geht an</small>
	    <h3>Staubige Kindheit</h3>
		</header>
	    <a href="#" class="dottedlink" >mehr darüber bei terre des hommes Deutschland</a>
</div>
<script type="text/javascript">
	jQuery(function(){
	new awesomebox('.lb1');
});
</script>
